# This file was generated by GoReleaser. DO NOT EDIT.
class Lazykubernetes < Formula
  desc ""
  homepage "https://github.com/yolossn/lazykubernetes"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/yolossn/lazykubernetes/releases/download/v0.1.0/lazykubernetes_Darwin_x86_64.zip"
    sha256 "438b7b356bbf5c19fa8f61133d79b4ce02f4fe76ad7729184f4757ceab737744"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/yolossn/lazykubernetes/releases/download/v0.1.0/lazykubernetes_Linux_x86_64.zip"
      sha256 "3206370ffb96698ba0b456c92eb5b9d8c28a351b43e66e19a3a21a78ae1212dd"
    end
  end

  def install
    bin.install "lazykubernetes"
  end

  test do
    system "#{bin}/lazykubernetes --version"
  end
end
