# This file was generated by GoReleaser. DO NOT EDIT.
class Lazykubernetes < Formula
  desc ""
  homepage "https://github.com/yolossn/lazykubernetes"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/yolossn/lazykubernetes/releases/download/v0.1.1/lazykubernetes_Darwin_x86_64.zip"
    sha256 "7d6a0461c2452b04ada86608636ba77758af326274155ded4b04cdfacc5ef412"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/yolossn/lazykubernetes/releases/download/v0.1.1/lazykubernetes_Linux_x86_64.zip"
      sha256 "cbd651456144540b64cc53f09073c4589f94b1b65f3819f341c379532c31da0e"
    end
  end

  def install
    bin.install "lazykubernetes"
  end

  test do
    system "#{bin}/lazykubernetes --version"
  end
end
